blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://docs.wrangles.io
    about: Check our documentation
  - name: ðŸ’¬ Support
    url: https://wrangleworks.com/support
    about: Contact support team
