name: Push to Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wrangleworks/wrangles
  IMAGE_TAG: latest

jobs:
  # pytest:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
  #       python-version: ['3.9', '3.10', '3.11', '3.12']
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pytest==7.4.4 lorem pytest-mock
  #         pip install -r requirements.txt
          
  #     - name: Run Tests
  #       run: pytest
  #       env:
  #         WRANGLES_USER: ${{ secrets.WRANGLES_USER }}
  #         WRANGLES_PASSWORD: ${{ secrets.WRANGLES_PASSWORD }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
  #         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  test-pip-install-macos-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.10']
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test pip install macos latest
        run: |
          python -m pip install --upgrade pip
          pip install .
          wrangles.recipe tests/samples/generate-data.wrgl.yml

  # test-pip-install:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-13]
  #       python-version: ['3.9', '3.10', '3.11', '3.12']
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Test pip install
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install .
  #         wrangles.recipe tests/samples/generate-data.wrgl.yml

  # test-generate-schema:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install Dependencies
  #       run: |
  #         pip install -r requirements.txt
  #         pip install jsonschema

  #     - name: Generate and Test Schema
  #       run: cd schema && python generate_recipe_schema.py

  #     - name: Save Schema as Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: schema
  #         path: schema/schema.json
  
  # build:
  #   runs-on: ubuntu-latest
  #   needs: [pytest, test-pip-install, test-generate-schema]
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     # Login against a Docker registry except on PR
  #     # https://github.com/docker/login-action
  #     - name: Log into registry ${{ env.REGISTRY }}
  #       if: github.event_name != 'pull_request'
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     # Extract metadata (tags, labels) for Docker
  #     # https://github.com/docker/metadata-action
  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #     # Build and push Docker image with Buildx (don't push on PR)
  #     # https://github.com/docker/build-push-action
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: ${{ github.event_name != 'pull_request' }}
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  #         labels: ${{ steps.meta.outputs.labels }}

  # test-container:
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'pull_request'
  #   needs: [build]
  #   container:
  #     image: ghcr.io/wrangleworks/wrangles:latest
  #   env:
  #     WRANGLES_USER: ${{ secrets.WRANGLES_USER }}
  #     WRANGLES_PASSWORD: ${{ secrets.WRANGLES_PASSWORD }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
  #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Remove wrangles folder
  #       run: rm -r wrangles

  #     - name: Install Test Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pytest==7.4.4 lorem pytest-mock
          
  #     - name: Run Tests
  #       run: pytest

  #     - name: Run Recipe (Remote)
  #       run: wrangles.recipe 42f319a8-0849-4177

  #     - name: Run Recipe (Local)
  #       run: >-
  #         cd tests/samples
  #         && wrangles.recipe recipe-basic.wrgl.yml
  #         && wrangles.recipe recipe_custom_function.wrgl.yml -f custom_functions.py
